[project]
name = "langchain-init"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "samTime101", email = "srijanregmi44@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "langchain[google-genai,openai]>=1.4.2",
]

[project.scripts]
langchain-init = "langchain_init:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
